spring:
  application:
    name: hakura-restaurant

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  key: hakura-secret-key-2024
